### ISSUE TITLE
As a team, we need to migrate the Merkle tree tracking all outbound messages to a separate contract to allow for easier upgrades

### ISSUE THREAD

**Issue by alexwhte** [connext/nxtp#1925] opened 2022-09-20 14:56 UTC
From epic #1808 
- [x]  Create the `Merkle` contract that allows public reads, but restricted writes. Should have the ability for the owner to update the writing address
- [x]  Update `SpokeConnector` to have a reference to a `Merkle` contract instead of inheriting it
- [x]  Update the `RootManager` to have a reference to a `Merkle` contract (no inherits)

**Comment by jakekidd** [comment] 2022-09-20 18:41
Duplicate of #1729

**Comment by jakekidd** [comment] 2022-09-20 18:41
transferring over the story points for this as well @alexwhte

**Comment by LayneHaber** [comment] 2022-09-22 18:22
reopening, not duplicate tasking

**Comment by jakekidd** [comment] 2022-09-27 02:29
This was completed as part of https://github.com/connext/nxtp/pull/1934

**Closed by jakekidd** 2022-09-27 02:29 UTC
Labels: enhancement 🧘, contract 💎, Story Points: 13
