### ISSUE TITLE
Sidebar transfers show different time estimates

### ISSUE THREAD

**Issue by just-a-node** [connext/nxtp#2870] opened 2022-12-26 20:00 UTC
**Describe the bug**

When sending a slow path txn (amount > destination router liquidity), the time estimate is 90 mins. 

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/01abd3f2-f1a2-47bf-bf00-3ac34fc0fe64)

But once the transfer is initiated, the sidebar transfer shows 4 min.

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/b3f518a6-6acb-4511-bc31-25a750f37da5)

These estimates should match. 

@alexwhte One potential thing to consider here: what if router liquidity increases after the user submits and then fast path is actually possible now? Should sidebar transfer update to fast estimate or stay as the same estimate at the time of transfer?

**Comment by pjenviri** [comment] 2022-12-28 15:20
It's because of the missing field `force_slow`., which is the exact root cause mentioned in https://app.zenhub.com/workspaces/connext-6272a34e0368a200141cd949/issues/gh/connext/nxtp/2825. So we don't know whether the transaction is the fast or slow path.

**Comment by alexwhte** [comment] 2023-01-04 03:18
@pjenviri Thanks I need to consider this UX more 
The current behavior of showing what is actually happening is correct

**Comment by alexwhte** [comment] 2023-01-04 03:41
closing for 2825

**Closed by alexwhte** 2023-01-04 03:41 UTC
Labels: bug 🐛, ui 🎨
