### ISSUE TITLE
[EXPLORER] Timer is not accurate

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2359] opened 2022-11-04 17:00 UTC
**Describe the bug**
When seeing the page for a pending transaction, the timer runs. When the transaction is received by the user, the time shown may be much less than what the timer was showing. Unsure if this is due to the local timer running and the site not querying often enough, or if it's due to a difference in time of the chains.

**To Reproduce**
1. Go to https://testnet.amarok.connextscan.io/
2. Open a processing transaction
3. See timer running while it's processing
4. Wait until transaction is received
5. See error (time difference between previously running timer and new time taken)

**Expected behavior**
The timer should be more accurate and maybe account for time differences between chains. Don't know how technically possible this is.

**Screenshots**
https://discord.com/channels/454734546869551114/1037738006779535370/1037738598033805362

**Comment by alexwhte** [comment] 2022-11-05 23:04
Closing as dduplicate of https://github.com/connext/nxtp/issues/2010

We are polling a function that has latency, and may instead fake it, optimize what we have, or poll subgraphs directly

**Closed by alexwhte** 2022-11-05 23:04 UTC
Labels: bug 🐛
