### ISSUE TITLE
[integration] Auction Error: "request (to router for bid) failed"

### ISSUE THREAD

**Issue by base0010** [connext/nxtp#191] opened 2021-08-10 21:42 UTC
Having this creep up in cyclical tests. router, messaging and node.js tester are all on the same box. Error happens intermittently

**Comment by LayneHaber** [comment] 2021-08-12 15:23
Router handling a bid:

```sh
[app] [1628730808387] INFO (0x627306090abaB3A6e1400e9345bC60c78a8BEf57/53924 on MacBook-Pro.local): Handled auction request
[app]     requestContext: {
[app]       "id": "tLQ6bHOqSkeN4bh3EGuLEQ/2544",
[app]       "origin": "subscribeToAuctionRequest"
[app]     }
```

sdk exiting auction

```sh
[1628730804410] INFO (SdkAgent/54508 on MacBook-Pro.local): Auction bids received
    method: "getTransferQuote"
    methodId: "0x3fde6661dab7a5be39a8b17b05ae3a41778435d0b0f30cc72958ef43961b1ffa"
    auctionBids: []
```

couple of things:
(1) we should fix the sdk logs to say theyre closing the auction
(2) its weird that the auction takes so long on the router, 6s should be plenty of time, and this is all local

**Comment by LayneHaber** [comment] 2021-08-16 18:45
Ah looks like this is the same as #213 -- my bad!

**Comment by LayneHaber** [comment] 2021-08-16 18:46
This is reproducible with all local services after about 5 min of running the cyclical tests. Could have something to do with the messaging subscriptions not being cleaned up properly

**Closed** 2021-08-17 09:45 UTC
