### ISSUE TITLE
[sdk] Don't expose direct connections to nats/auth when initializing sdk

### ISSUE THREAD

**Issue by ArjunBhuptani** [connext/nxtp#64] opened 2021-07-22 15:02 UTC
Instead of these:
- `natsUrl`: Optional. Override NATS URL otherwise connect to the main, global NATS cluster.
- `authUrl`: Optional. Override auth URL otherwise connect to the main, global auth server.

We should just have a simple:
- `network`: Optional. `testnet` or `mainnet` - defaults to `mainnet`.

Exposing nats/auth will not be backwards compatible when we move to more decentralized messaging and is unnecessary cognitive overhead for the developer.

**Comment by rhlsthrm** [comment] 2021-07-23 09:35
This isn't for users, but we need a way to override with local stuff.

**Comment by ArjunBhuptani** [comment] 2021-07-24 21:27
just have a `network` `local` option?

**Comment by rhlsthrm** [comment] 2021-07-25 06:16
Sure, I'll add that. I think I'll also have an optional override with manual nats/auth url and not expose this to users.

**Comment by rhlsthrm** [comment] 2021-08-03 15:14
Duplicate of #76

**Closed by rhlsthrm** 2021-08-03 15:14 UTC
