### ISSUE TITLE
Significant delay in latest transfer card showing up

### ISSUE THREAD

**Issue by Tommy-R8** [connext/nxtp#2346] opened 2022-11-04 04:31 UTC
**Describe the bug**
The latest transfer card with the current processing one doesn't show up for a long time (around 1-2 min depending on the tx confirmation time). I suppose this is the time it takes for the transaction to get confirmed + the subgraph seeing the event.

**To Reproduce**
1. Go to https://amarok-testnet.coinhippo.io/
2. Swap

**Expected behavior**
The card with the current pending transaction should show up immediately upon clicking confirm on metamask.

**Comment by Tommy-R8** [comment] 2022-11-04 06:45
Also possibly remove the "transferring TEST..." entirely and just leave the card with the processing transaction on the latest transfers list

**Comment by alexwhte** [comment] 2022-11-05 23:29
Latency is same delay from polling the backend and dupe of this shttps://github.com/connext/nxtp/issues/2010

Good callout. Need to update this interaction

**Closed by alexwhte** 2022-11-05 23:29 UTC
Labels: bug 🐛, ui 🎨
